# Generated by Django 4.0.1 on 2022-02-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kitchenstaffprofile'),
        ('users', '0007_staffprofile'),
    ]

    operations = [
    ]
