# Generated by Django 4.0.2 on 2022-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ticket_tickettracker_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cover_img',
            field=models.URLField(default='https://res.cloudinary.com/decameal/image/upload/v1645016151/MealThumbnails/food_c1rmga.png'),
        ),
    ]
