# Generated by Django 4.0.2 on 2022-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_meal_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='scheduled_date',
            field=models.DateField(unique=True),
        ),
    ]
